Repository bee-queue/arena, pull requests merged in 2020-11, with the labels that each got.

#251 add support for bullmq
  src/server/queue/index.js
  src/server/views/dashboard/queueDetails.js
  src/server/views/helpers/queueHelpers.js
Labels: bullmq, enhancement

#273 bullmq docs: update readme docs
  README.md
Labels: documentation

#294 Support redis connection options in BullMQ
  src/server/queue/index.js
Labels: bug, bullmq
